#!/usr/bin/python3

def raise_exception_msg(message=""):
    try:
        pass
    finally:
        raise NameError(message)
